apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: shopsphere
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/OWNER/shopsphere-user-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017"
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
